---
# tasks file for docker
- name: add the apt signing key for docker
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD8576A8BA88D21E9 id=A88D21E9

- name: add the docker repository from a template
  template: src=saucy.list dest=/etc/apt/sources.list.d/docker.list owner=root group=root mode=0644

- name: install the docker package
  apt: name=lxc-docker state=present update_cache=yes
