---
# tasks file for docker
- name: add the apt signing key for docker
  apt_key: url={{ docker_apt_key_url }} id={{ docker_apt_key_id }}

- name: add the docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: install the docker package
  apt: name={{ docker_pkg_name }} state=present update_cache=yes

- name: start registry image
  docker: image=registry ports=5000
  when: docker_registry == "True"
