---
# tasks file for docker
- name: add the apt signing key for docker
  apt_key: url={{ docker_apt_key_url }} id=(( docker_apt_key_id }}

- name: add the docker repository from a template
  template: src=saucy.list dest=/etc/apt/sources.list.d/docker.list owner=root group=root mode=0644

- name: install the docker package
  apt: name={{ docker_pkg_name }} state=present update_cache=yes
